apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
      - name: post-service
        image: uniunity/post-service:v1.8.1  
        imagePullPolicy: Always
        ports:
        - containerPort: 3000       
        env:
        - name: RABBIT
          value: amqp://rabbitmq:5672
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: post-service-db-secret
              key: POST_SERVICE_DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: post-service-db-secret
              key: POST_SERVICE_DB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: post-service-db-secret
              key: POST_SERVICE_DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: post-service-db-secret
              key: POST_SERVICE_DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: post-service-db-secret
              key: POST_SERVICE_DB_DATABASE       