apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              until nc -z partner-service-db 3306; do
                echo "Waiting for partner-service-db…"
                sleep 2
              done
        - name: wait-for-rabbitmq
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              until nc -z rabbitmq 5672; do
                echo "Waiting for rabbitmq…"
                sleep 2
              done
      containers:
      - name: post-service
        image: uniunity/post-service:202506100102
        ports:
        - containerPort: 3000       
        env:
        - name: RABBIT
          value: amqp://rabbitmq:5672
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: post-service-db-secret
              key: POST_SERVICE_DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: post-service-db-secret
              key: POST_SERVICE_DB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: post-service-db-secret
              key: POST_SERVICE_DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: post-service-db-secret
              key: POST_SERVICE_DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: post-service-db-secret
              key: POST_SERVICE_DB_DATABASE
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: "guest"
        - name: RABBITMQ_PASSWORD
          value: "guest"
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 3       