apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-reaction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-reaction-service
  template:
    metadata:
      labels:
        app: post-reaction-service
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              until nc -z post-reaction-service-db 3306; do
                echo "Waiting for post-reaction-service-db"
                sleep 2
              done
        - name: wait-for-rabbitmq
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              until nc -z rabbitmq 5672; do
                echo "Waiting for rabbitmq…"
                sleep 2
              done
      containers:
      - name: post-reaction-service
        image: uniunity/post-reaction-service:202506051700
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        env:
        - name: DB_HOST
          value: post-reaction-service-db
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: post-reaction-service-db-secret
              key: POST_REACTION_SERVICE_DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: post-reaction-service-db-secret
              key: POST_REACTION_SERVICE_DB_PASSWORD
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: post-reaction-service-db-secret
              key: POST_REACTION_SERVICE_DB_DATABASE
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: "guest"
        - name: RABBITMQ_PASSWORD
          value: "guest"
        readinessProbe:
          httpGet:
            path: /ready
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 3
