resources:
- deployment.yaml

images:
- name: uniunity/post-reaction-service
  newName: uniunity/post-reaction-service
  newTag: "202506141314"
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
