apiVersion: v1
kind: Service
metadata:
  name: post-reaction-service
spec:
  selector:
    app: post-reaction-service
  ports:
    - protocol: TCP
      port: 3002       
      targetPort: 3002 
  type: ClusterIP
