apiVersion: apps/v1
kind: Deployment
metadata:
  name: partner-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: partner-service
  template:
    metadata:
      labels:
        app: partner-service
    spec:
      containers:
      - name: partner-service
        image: uniunity/partner-service:v0.6
        ports:
        - containerPort: 3003
