apiVersion: apps/v1
kind: Deployment
metadata:
  name: partner-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: partner-service
  template:
    metadata:
      labels:
        app: partner-service
    spec:
      containers:
      - name: partner-service
        image: uniunity/partner-service:v0.4
        ports:
        - containerPort: 3003
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3003
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /healthz
            port: 3003
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 3
