apiVersion: apps/v1
kind: Deployment
metadata:
  name: partner-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: partner-service-db
  template:
    metadata:
      labels:
        app: partner-service-db
    spec:
      containers:
        - name: partner-service-db
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: partner-service-db-secret
                  key: PARTNER_SERVICE_DB_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: partner-service-db-secret
                  key: PARTNER_SERVICE_DB_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: partner-service-db-secret
                  key: PARTNER_SERVICE_DB_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: partner-service-db-secret
                  key: PARTNER_SERVICE_DB_DATABASE
          ports:
            - containerPort: 3306
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
              ephemeral-storage: "500Mi"
            limits:
              memory: "512Mi"
              cpu: "250m"
              ephemeral-storage: "1Gi"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: partner-service-db-storage
            - mountPath: /docker-entrypoint-initdb.d
              name: init-sql
              readOnly: true

      volumes:
        - name: partner-service-db-storage
          persistentVolumeClaim:
            claimName: partner-service-db-pvc
        - name: init-sql
          configMap:
            name: partner-service-db-init-sql
