apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-reaction-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-reaction-service-db
  template:
    metadata:
      labels:
        app: post-reaction-service-db
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: post-reaction-service-db-secret
                  key: POST_REACTION_SERVICE_DB_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: post-reaction-service-db-secret
                  key: POST_REACTION_SERVICE_DB_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: post-reaction-service-db-secret
                  key: POST_REACTION_SERVICE_DB_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: post-reaction-service-db-secret
                  key: POST_REACTION_SERVICE_DB_DATABASE
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: post-reaction-service-db-secret
                  key: POST_REACTION_SERVICE_DB_HOST
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: post-reaction-service-db-secret
                  key: POST_REACTION_SERVICE_DB_PORT
          volumeMounts:
            - name: post-reaction-db-storage
              mountPath: /var/lib/mysql
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      volumes:
        - name: post-reaction-db-storage
          persistentVolumeClaim:
            claimName: post-reaction-service-db-pvc
        - name: init-sql
          configMap:
            name: post-reaction-init-configmap
            items:
              - key: post-reaction-init.sql
                path: post-reaction-init.sql
