apiVersion: v1
kind: Service
metadata:
  name: post-reaction-service-db
spec:
  selector:
    app: post-reaction-service-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
