apiVersion: v1
kind: Secret
metadata:
  name: partner-service-db-secret
type: Opaque
stringData:
  PARTNER_SERVICE_DB_ROOT_PASSWORD: rootpass
  PARTNER_SERVICE_DB_USER: partner
  PARTNER_SERVICE_DB_PASSWORD: partnerpass
  PARTNER_SERVICE_DB_DATABASE: partner_service_db
  PARTNER_SERVICE_DB_HOST: partner-service-db
  PARTNER_SERVICE_DB_PORT: "3306"                    
