apiVersion: v1
kind: Secret
metadata:
  name: post-service-db-secret
type: Opaque
stringData:
  POST_SERVICE_DB_ROOT_PASSWORD: rootpass
  POST_SERVICE_DB_USER: post
  POST_SERVICE_DB_PASSWORD: postpass
  POST_SERVICE_DB_DATABASE: post_service_db
  POST_SERVICE_DB_HOST: post-service-db
  POST_SERVICE_DB_PORT: "3306"