apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uniunity-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: uniunity
    http:
      paths:
      - path: /partner(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: partner-service
            port:
              number: 3003
      - path: /retailer(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: partner-service
            port:
              number: 3003
