apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              until nc -z user-service-db 3306; do
                echo "Waiting for user-service-db…"
                sleep 2
              done
        - name: wait-for-rabbitmq
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              until nc -z rabbitmq 5672; do
                echo "Waiting for rabbitmq…"
                sleep 2
              done      
      containers:
      - name: user-service
        image: uniunity/user-service:202506131144
        ports:
        - containerPort: 3004
        env:
        - name: DB_HOST
          value: "user-service-db"
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: "user_user"
        - name: DB_PASSWORD
          value: "user_password"
        - name: DB_NAME
          value: "user_service_db"
        - name: RABBIT
          value: "amqp://guest:guest@rabbitmq:5672"
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: "guest"
        - name: RABBITMQ_PASSWORD
          value: "guest"
        - name: JWT_SECRET
          value: "uni-unity"
        - name: ACCESS_TOKEN_EXPIRES_IN
          value: "50m"
        - name: REFRESH_TOKEN_EXPIRES_IN
          value: "7d"
        readinessProbe:
          httpGet:
            path: /ready
            port: 3004
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 3
