apiVersion: apps/v1
kind: Deployment
metadata:
  name: start-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: start-service
  template:
    metadata:
      labels:
        app: start-service
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              until nc -z start-service-db 3306; do
                echo "Waiting for start-service-db…"
                sleep 2
              done
        - name: wait-for-rabbitmq
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              until nc -z rabbitmq 5672; do
                echo "Waiting for rabbitmq…"
                sleep 2
              done
      containers:
      - name: start-service
        image: uniunity/start-service:lastest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: MYSQL_HOST
          value: start-service-db
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: start-service-db-secret
              key: START_SERVICE_DB_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: start-service-db-secret
              key: START_SERVICE_DB_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: start-service-db-secret
              key: START_SERVICE_DB_DATABASE
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: RABBITMQ_PORT
          value: "5672"
