apiVersion: apps/v1
kind: Deployment
metadata:
  name: start-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: start-service
  template:
    metadata:
      labels:
        app: start-service
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              until nc -z rabbitmq 5672; do
                echo "Waiting for rabbitmq…"
                sleep 2
              done
      containers:
      - name: start-service
        image: uniunity/start-service:202506080220
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          value: "guest"
        - name: RABBITMQ_PASSWORD
          value: "guest"
        readinessProbe:
          httpGet:
            path: /ready
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 3
