apiVersion: apps/v1
kind: Deployment
metadata:
  name: start-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: start-service
  template:
    metadata:
      labels:
        app: start-service
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              until nc -z partner-service-db 3306; do
                echo "Waiting for partner-service-db…"
                sleep 2
              done
        - name: wait-for-rabbitmq
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              until nc -z rabbitmq 5672; do
                echo "Waiting for rabbitmq…"
                sleep 2
              done
      containers:
      - name: start-service
        image: uniunity/start-service:v0.17
        ports:
        - containerPort: 3001
        env:
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: RABBITMQ_PORT
          value: "5672"
