apiVersion: apps/v1
kind: Deployment
metadata:
  name: start-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: start-service
  template:
    metadata:
      labels:
        app: start-service
    spec:
      containers:
      - name: start-service
        image: uniunity/start-service:v0.17
        ports:
        - containerPort: 3001
        env:
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: RABBITMQ_PORT
          value: "5672"
