apiVersion: v1
kind: ConfigMap
metadata:
  name: post-reaction-init-configmap
data:
  post-reaction-init.sql: |
    SET character_set_client = utf8mb4;
    SET character_set_connection = utf8mb4;
    SET character_set_results = utf8mb4;

    CREATE DATABASE IF NOT EXISTS post_reaction_service_db;
    USE post_reaction_service_db;

    CREATE TABLE Comment (
      comment_id INT auto_increment PRIMARY KEY NOT NULL,
      comment_content TEXT NOT NULL,
      comment_date VARCHAR(255) NOT NULL,
      like_count_comment INT NOT NULL,
      user_email VARCHAR(255) NOT NULL,
      post_id INT NOT NULL
    );

    CREATE TABLE Heart (
      heart_id INT auto_increment PRIMARY KEY NOT NULL,
      created_at VARCHAR(255) NOT NULL,
      user_email VARCHAR(255) NOT NULL,
      post_id INT NOT NULL
    );

    CREATE TABLE Scrap (
      scrap_id INT auto_increment PRIMARY KEY NOT NULL,
      created_at VARCHAR(255) NOT NULL,
      user_email VARCHAR(255) NOT NULL,
      post_id INT NOT NULL
    );

    ALTER TABLE Heart MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
    ALTER TABLE Scrap MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

  

